name: Docker Image Build

on:
  push:
    branches: [ master ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./strapi
          file: ./Dockerfile
          push: true
          tags: egahmad/strapi-docker:latest
          build-args: |
            STRAPI_VERSION=4.0.7
            BASE_VERSION=latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
